export type TxType = "inflow" | "outflow";
export type Transaction = { id:string; date:string; type:TxType; category:string; description:string; amount:number; account:string; method:string; reference?:string; notes?:string; receipt?:string; status:"posted"|"voided"|"needs_review"; batchId?:string };
export type BudgetLine = { item:number; name:string; type:TxType; amount:number; prior:number; rationale?:string; group?:string };

const raw: Array<[number,string,TxType,number,string?,string?]> = [
[1,"Dues","inflow",33500,"110 existing members × $250 plus 20 new members × $300. Total: $33,500."],
[2,"Refreshments","inflow",6762,"$138 per meeting × 49 meetings."],[3,"Raffle","inflow",5500,"Approximately $112.30 per meeting × 49 meetings."],[4,"Fines","inflow",400],[5,"Club 1600 Pins","inflow",300],[6,"Installation","inflow",4000,undefined,"installation"],[7,"Ladies Night","inflow",4500,undefined,"ladies-night"],[8,"Neil Percentie Back to School","inflow",3000,undefined,"back-to-school"],[9,"Miscellaneous","inflow",500],[10,"Family Fun Day","inflow",500,undefined,"family-fun-day"],[11,"Ed Carey Boil Fish Run","inflow",1000,undefined,"boil-fish"],[12,"Socials","inflow",3500,undefined,"socials"],[13,"Night of Past Presidents","inflow",1000,undefined,"past-presidents"],[14,"In Club Leadership Tour","inflow",1600,undefined,"leadership-tour"],[15,"Membership Drives","inflow",500,undefined,"membership-drives"],[16,"Corporate Donations","inflow",500],[17,"High School Speech Contest – Sponsorship/Ads","inflow",2051,undefined,"speech-contest"],[18,"The Pitch / Business Workshop – October","inflow",300,undefined,"the-pitch"],
[19,"International Dues Paid to TI","outflow",18620,"Budgeted at $18,620 based on the approved dues calculation."],[20,"Room Rental","outflow",7350,"Red Cross venue: $150 × 49 meetings."],[21,"Ladies Night","outflow",4500,undefined,"ladies-night"],[22,"Installation Expenses","outflow",4000,undefined,"installation"],[23,"National Club Leadership Tour","outflow",1845],[24,"Socials","outflow",3500,undefined,"socials"],[25,"Neil Percentie Back to School","outflow",3000,undefined,"back-to-school"],[26,"LAB Expenses","outflow",1522],[27,"Executive Travel","outflow",1217],[28,"Public Relations","outflow",1763],[29,"Refreshments","outflow",2500,"Approximately $51.02 × 49 meetings."],[30,"Community Events","outflow",532],[31,"Membership Expenses","outflow",1232],[32,"Nights of Past Presidents","outflow",1000,undefined,"past-presidents"],[33,"Raffle Gifts","outflow",1325],[34,"Education Expenses","outflow",761],[35,"Ed Carey Boil Fish Run","outflow",1000,undefined,"boil-fish"],[36,"Family Fun Day","outflow",500,undefined,"family-fun-day"],[37,"Basketball Tournament","outflow",913],[38,"New Members Orientation","outflow",1141],[39,"Newsletter","outflow",609],[40,"Bank Charges","outflow",350],[41,"Awards","outflow",1250],[42,"Miscellaneous","outflow",343],[43,"Youth Leadership Programs","outflow",1552],[44,"Leadership Awards","outflow",381],[45,"In Club Leadership Tour","outflow",1600,undefined,"leadership-tour"],[46,"Membership Drives","outflow",500,undefined,"membership-drives"],[47,"Panel Discussion","outflow",1445],[48,"Speechcraft","outflow",411],[49,"Legacy Leadership Banquet","outflow",400],[50,"High School Speech Contest","outflow",2051,undefined,"speech-contest"],[51,"The Pitch / Business Workshop – October","outflow",300,undefined,"the-pitch"]];
export const budget: BudgetLine[] = raw.map(([item,name,type,amount,rationale,group])=>({item,name,type,amount,prior:amount,rationale,group}));
export const demoTransactions: Transaction[] = [
{id:"t1",date:"2026-07-07",type:"inflow",category:"Refreshments",description:"Weekly meeting collections",amount:142,account:"Operating account",method:"Cash",status:"posted",batchId:"meeting-0707"},
{id:"t2",date:"2026-07-07",type:"inflow",category:"Raffle",description:"Weekly meeting collections",amount:118,account:"Operating account",method:"Cash",status:"posted",batchId:"meeting-0707"},
{id:"t3",date:"2026-07-07",type:"inflow",category:"Fines",description:"Weekly meeting collections",amount:11,account:"Operating account",method:"Cash",status:"posted",batchId:"meeting-0707"},
{id:"t4",date:"2026-07-12",type:"outflow",category:"Room Rental",description:"Red Cross venue — July",amount:600,account:"Operating account",method:"Bank transfer",reference:"RR-0726",receipt:"receipt.pdf",status:"posted"},
{id:"t5",date:"2026-08-03",type:"outflow",category:"Public Relations",description:"Club banner printing",amount:310,account:"Operating account",method:"Card",receipt:"receipt.jpg",status:"posted"},
{id:"t6",date:"2026-08-11",type:"inflow",category:"Corporate Donations",description:"Community programme donation",amount:500,account:"Operating account",method:"Cheque",reference:"1042",status:"posted"},
{id:"t7",date:"2026-08-23",type:"outflow",category:"Neil Percentie Back to School",description:"School supply purchase",amount:2440,account:"Operating account",method:"Card",receipt:"receipt.pdf",status:"posted"},
{id:"t8",date:"2026-09-02",type:"outflow",category:"Bank Charges",description:"Monthly service fees",amount:42.5,account:"Operating account",method:"Direct debit",status:"posted"},
];
export type Member = {id:string;name:string;type:"Existing"|"New";expected:number;payments:{date:string;amount:number;method:string}[];special?:"Covered by Club"|"Exempt / Waived"};
export const demoMembers: Member[] = [
{id:"m1",name:"Amar Pearson",type:"Existing",expected:250,payments:[{date:"2026-07-10",amount:150,method:"Bank transfer"},{date:"2026-08-14",amount:100,method:"Bank transfer"}]},
{id:"m2",name:"Danielle Moss",type:"New",expected:300,payments:[{date:"2026-07-18",amount:150,method:"Cash"}]},
{id:"m3",name:"Marcus Rolle",type:"Existing",expected:250,payments:[]},
{id:"m4",name:"Claudia Johnson",type:"Existing",expected:250,payments:[],special:"Covered by Club"},
{id:"m5",name:"Renee Brown",type:"Existing",expected:250,payments:[{date:"2026-08-04",amount:250,method:"Cheque"}]},
];
export const money=(n:number)=>new Intl.NumberFormat("en-BS",{style:"currency",currency:"BSD",minimumFractionDigits:2}).format(n);
export const pct=(n:number)=>`${Math.round(n)}%`;
export const monthIndex=(date:string)=>{ if(date<"2026-07-01"||date>"2027-06-30") return -1; const d=new Date(`${date}T12:00:00`); return (d.getMonth()+6)%12};
export const quarterFor=(date:string)=>{const month=monthIndex(date); return month<0?"Outside program year":`Q${Math.floor(month/3)+1}`};
