-- Club 1600 Treasury: one source of truth, July–June reporting, protected financial records.
create extension if not exists pgcrypto;
create type public.app_role as enum ('admin','treasurer','viewer');
create type public.money_direction as enum ('inflow','outflow');
create type public.record_status as enum ('posted','voided','needs_review');
create type public.member_type as enum ('existing','new');
create type public.dues_status as enum ('active','covered_by_club','exempt_waived');

create table public.profiles (id uuid primary key default gen_random_uuid(), user_id uuid unique not null references auth.users(id) on delete cascade, full_name text not null, email text not null, role app_role not null default 'viewer', created_at timestamptz not null default now());
create table public.program_years (id uuid primary key default gen_random_uuid(), name text unique not null, start_date date not null, end_date date not null, opening_balance numeric(12,2), is_active boolean not null default false, check(end_date>start_date));
create table public.categories (id uuid primary key default gen_random_uuid(), item_number int unique not null, name text not null, type money_direction not null, group_key text, active boolean not null default true, unique(name,type));
create table public.budget_lines (id uuid primary key default gen_random_uuid(), program_year_id uuid not null references public.program_years(id), category_id uuid not null references public.categories(id), budget_amount numeric(12,2) not null check(budget_amount>=0), prior_year_budget numeric(12,2) check(prior_year_budget>=0), rationale text, unique(program_year_id,category_id));
create table public.treasury_accounts (id uuid primary key default gen_random_uuid(), name text unique not null, type text not null, opening_balance numeric(12,2), active boolean not null default true);
create table public.transactions (id uuid primary key default gen_random_uuid(), program_year_id uuid not null references public.program_years(id), transaction_date date, type money_direction not null, category_id uuid references public.categories(id), account_id uuid references public.treasury_accounts(id), description text not null, counterparty text, amount numeric(12,2) not null check(amount>0), payment_method text, reference text, notes text, receipt_path text, status record_status not null default 'posted', batch_id uuid, created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), voided_at timestamptz, voided_by uuid references auth.users(id), void_reason text, check(status<>'voided' or (voided_at is not null and voided_by is not null and length(trim(void_reason))>0)));
create table public.members (id uuid primary key default gen_random_uuid(), full_name text not null, member_type member_type not null, active boolean not null default true, notes text);
create table public.member_program_years (id uuid primary key default gen_random_uuid(), member_id uuid not null references public.members(id), program_year_id uuid not null references public.program_years(id), expected_dues numeric(12,2) not null check(expected_dues>=0), dues_status dues_status not null default 'active', notes text, unique(member_id,program_year_id));
create table public.dues_payments (id uuid primary key default gen_random_uuid(), member_program_year_id uuid not null references public.member_program_years(id), payment_date date, amount numeric(12,2) not null check(amount>0), account_id uuid references public.treasury_accounts(id), payment_method text, reference text, notes text, status record_status not null default 'posted', created_by uuid references auth.users(id), created_at timestamptz not null default now(), check(status='needs_review' or payment_date is not null));
create table public.audit_log (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id), action text not null, entity_type text not null, entity_id uuid not null, old_values jsonb, new_values jsonb, created_at timestamptz not null default now());

create or replace function public.current_role() returns app_role language sql stable security definer set search_path=public as $$ select role from profiles where user_id=auth.uid() $$;
create or replace function public.guard_program_year_date() returns trigger language plpgsql as $$ declare py program_years%rowtype; begin select * into py from program_years where id=new.program_year_id; if new.transaction_date is null then new.status='needs_review'; elsif new.transaction_date<py.start_date or new.transaction_date>py.end_date then raise exception 'Transaction date is outside the selected program year'; end if; return new; end $$;
create trigger transactions_program_year before insert or update of transaction_date,program_year_id on public.transactions for each row execute function public.guard_program_year_date();
create or replace function public.audit_changes() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into audit_log(user_id,action,entity_type,entity_id,old_values,new_values) values(auth.uid(),lower(tg_op),tg_table_name,coalesce(new.id,old.id),case when tg_op<>'INSERT' then to_jsonb(old) end,case when tg_op<>'DELETE' then to_jsonb(new) end); return coalesce(new,old); end $$;
create trigger audit_transactions after insert or update on transactions for each row execute function audit_changes();
create trigger audit_dues after insert or update on dues_payments for each row execute function audit_changes();
create trigger audit_budgets after insert or update on budget_lines for each row execute function audit_changes();
create trigger audit_obligations after insert or update on member_program_years for each row execute function audit_changes();

create view public.financial_ledger with (security_invoker=true) as
select t.id,t.program_year_id,t.transaction_date,t.type,c.name category,t.description,t.amount,t.account_id,t.payment_method,t.reference,t.notes,t.status,'transaction'::text source from transactions t join categories c on c.id=t.category_id where t.status='posted'
union all
select d.id,mp.program_year_id,d.payment_date,'inflow'::money_direction,'Dues',('Dues — '||m.full_name),d.amount,d.account_id,d.payment_method,d.reference,d.notes,d.status,'dues_payment' from dues_payments d join member_program_years mp on mp.id=d.member_program_year_id join members m on m.id=mp.member_id where d.status='posted' and d.payment_date is not null;

alter table profiles enable row level security; alter table program_years enable row level security; alter table categories enable row level security; alter table budget_lines enable row level security; alter table treasury_accounts enable row level security; alter table transactions enable row level security; alter table members enable row level security; alter table member_program_years enable row level security; alter table dues_payments enable row level security; alter table audit_log enable row level security;
create policy "authenticated read profiles" on profiles for select to authenticated using(true);
create policy "authenticated read years" on program_years for select to authenticated using(true); create policy "admin manage years" on program_years for all to authenticated using(current_role()='admin') with check(current_role()='admin');
create policy "authenticated read categories" on categories for select to authenticated using(true); create policy "finance manage categories" on categories for all to authenticated using(current_role() in ('admin','treasurer')) with check(current_role() in ('admin','treasurer'));
create policy "authenticated read budgets" on budget_lines for select to authenticated using(true); create policy "finance manage budgets" on budget_lines for all to authenticated using(current_role() in ('admin','treasurer')) with check(current_role() in ('admin','treasurer'));
create policy "authenticated read accounts" on treasury_accounts for select to authenticated using(true); create policy "admin manage accounts" on treasury_accounts for all to authenticated using(current_role()='admin') with check(current_role()='admin');
create policy "authenticated read transactions" on transactions for select to authenticated using(true); create policy "finance insert transactions" on transactions for insert to authenticated with check(current_role() in ('admin','treasurer') and created_by=auth.uid()); create policy "finance update transactions" on transactions for update to authenticated using(current_role() in ('admin','treasurer')) with check(current_role() in ('admin','treasurer'));
create policy "authenticated read members" on members for select to authenticated using(true); create policy "finance manage members" on members for all to authenticated using(current_role() in ('admin','treasurer')) with check(current_role() in ('admin','treasurer'));
create policy "authenticated read obligations" on member_program_years for select to authenticated using(true); create policy "finance manage obligations" on member_program_years for all to authenticated using(current_role() in ('admin','treasurer')) with check(current_role() in ('admin','treasurer'));
create policy "authenticated read dues" on dues_payments for select to authenticated using(true); create policy "finance insert dues" on dues_payments for insert to authenticated with check(current_role() in ('admin','treasurer') and created_by=auth.uid()); create policy "finance update dues" on dues_payments for update to authenticated using(current_role() in ('admin','treasurer')) with check(current_role() in ('admin','treasurer'));
create policy "admin read audit" on audit_log for select to authenticated using(current_role()='admin');
insert into storage.buckets(id,name,public) values('receipts','receipts',false) on conflict(id) do update set public=false;
create policy "read receipts" on storage.objects for select to authenticated using(bucket_id='receipts'); create policy "write receipts" on storage.objects for insert to authenticated with check(bucket_id='receipts' and public.current_role() in ('admin','treasurer')); create policy "replace receipts" on storage.objects for update to authenticated using(bucket_id='receipts' and public.current_role() in ('admin','treasurer'));
